### PR TITLE
Add default export for useSt8

### PR DESCRIPTION
**Pull request by isaiahgrey93**
Nice work! I really like the consolidated approach to `useState`.
Thank you for this 🎉 

Just opening this to see if you would consider adding a default export to allow users a way to name the function whatever they'd like vs aliasing the named export.

### CODE REVIEW

**Comment by mweststrate** [comment]
@isaiahgrey93 nice! would you mind explaining it shortly in the readme as well? Thanks!

**Comment by isaiahgrey93** [comment]
Sure thing! I updated with details for the default export. Also I noticed:
```javascript
import { useSt8 } from 'useSt8';
```
**vs**
```javascript
import useSt8 from 'useSt8';
```
is a whole 4 characters less! 😆

**Comment by mweststrate** [comment]
Thanks!

**Comment by mweststrate** [comment]
Released as 1.0.2

**Pull request merged**
